-- =========================================================================
-- 0036_master_cities_v2.sql
--
-- Operator-provided master roster of nightlife markets. Idempotent on
-- (country_code, region, name) — safe to re-run. Cities not in this
-- list are NOT archived here; archive manually if you want to hide one.
-- =========================================================================

-- Countries this list references
INSERT INTO countries (code, name, default_currency) VALUES
  ('AU', 'Australia', 'AUD'),
  ('CA', 'Canada', 'CAD'),
  ('CZ', 'Czech Republic', 'CZK'),
  ('DE', 'Germany', 'EUR'),
  ('ES', 'Spain', 'EUR'),
  ('GB', 'United Kingdom', 'GBP'),
  ('GR', 'Greece', 'EUR'),
  ('HU', 'Hungary', 'HUF'),
  ('IE', 'Ireland', 'EUR'),
  ('IT', 'Italy', 'EUR'),
  ('NL', 'Netherlands', 'EUR'),
  ('NZ', 'New Zealand', 'NZD'),
  ('PT', 'Portugal', 'EUR'),
  ('US', 'United States', 'USD')
ON CONFLICT (code) DO NOTHING;

-- Cities — region is NULL for non-US/CA entries by design
INSERT INTO cities (country_code, region, name, timezone) VALUES
  ('AU', NULL, 'Adelaide', 'Australia/Adelaide'),
  ('US', 'Ohio', 'Akron', 'America/New_York'),
  ('US', 'New York', 'Albany', 'America/New_York'),
  ('US', 'New Mexico', 'Albuquerque', 'America/Denver'),
  ('NL', NULL, 'Amsterdam', 'Europe/Amsterdam'),
  ('US', 'California', 'Anaheim', 'America/Los_Angeles'),
  ('US', 'Michigan', 'Ann Arbor', 'America/Detroit'),
  ('US', 'Texas', 'Arlington', 'America/Chicago'),
  ('US', 'Georgia', 'Athens', 'America/New_York'),
  ('GR', NULL, 'Athens', 'Europe/Athens'),
  ('US', 'Georgia', 'Atlanta', 'America/New_York'),
  ('NZ', NULL, 'Auckland', 'Pacific/Auckland'),
  ('US', 'Georgia', 'Augusta', 'America/New_York'),
  ('US', 'Texas', 'Austin', 'America/Chicago'),
  ('US', 'California', 'Bakersfield', 'America/Los_Angeles'),
  ('US', 'Maryland', 'Baltimore', 'America/New_York'),
  ('ES', NULL, 'Barcelona', 'Europe/Madrid'),
  ('US', 'Louisiana', 'Baton Rouge', 'America/Chicago'),
  ('GB', NULL, 'Belfast', 'Europe/London'),
  ('DE', NULL, 'Berlin', 'Europe/Berlin'),
  ('US', 'Montana', 'Billings', 'America/Denver'),
  ('US', 'Alabama', 'Birmingham', 'America/Chicago'),
  ('GB', NULL, 'Birmingham', 'Europe/London'),
  ('GB', NULL, 'Blackpool', 'Europe/London'),
  ('US', 'Indiana', 'Bloomington', 'America/Indiana/Indianapolis'),
  ('US', 'Idaho', 'Boise', 'America/Boise'),
  ('US', 'Massachusetts', 'Boston', 'America/New_York'),
  ('US', 'Colorado', 'Boulder', 'America/Denver'),
  ('GB', NULL, 'Bournemouth', 'Europe/London'),
  ('US', 'Kentucky', 'Bowling Green', 'America/New_York'),
  ('US', 'Montana', 'Bozeman', 'America/Denver'),
  ('AU', NULL, 'Brisbane', 'Australia/Brisbane'),
  ('GB', NULL, 'Bristol', 'Europe/London'),
  ('US', 'New York', 'Brooklyn', 'America/New_York'),
  ('HU', NULL, 'Budapest', 'Europe/Budapest'),
  ('US', 'New York', 'Buffalo', 'America/New_York'),
  ('AU', NULL, 'Byron Bay', 'Australia/Sydney'),
  ('AU', NULL, 'Cairns', 'Australia/Brisbane'),
  ('CA', 'Alberta', 'Calgary', 'America/Edmonton'),
  ('AU', NULL, 'Canberra', 'Australia/Sydney'),
  ('GB', NULL, 'Cardiff', 'Europe/London'),
  ('US', 'North Carolina', 'Chapel Hill', 'America/New_York'),
  ('US', 'South Carolina', 'Charleston', 'America/New_York'),
  ('US', 'West Virginia', 'Charleston', 'America/New_York'),
  ('US', 'North Carolina', 'Charlotte', 'America/New_York'),
  ('US', 'Tennessee', 'Chattanooga', 'America/Chicago'),
  ('US', 'Illinois', 'Chicago - River North', 'America/Chicago'),
  ('US', 'Illinois', 'Chicago - West Loop', 'America/Chicago'),
  ('NZ', NULL, 'Christchurch', 'Pacific/Auckland'),
  ('US', 'Ohio', 'Cincinnati', 'America/New_York'),
  ('US', 'Ohio', 'Cleveland', 'America/New_York'),
  ('US', 'Missouri', 'Columbia', 'America/Chicago'),
  ('US', 'South Carolina', 'Columbia', 'America/New_York'),
  ('US', 'Ohio', 'Columbus', 'America/New_York'),
  ('IE', NULL, 'Cork', 'Europe/Dublin'),
  ('US', 'Texas', 'Dallas', 'America/Chicago'),
  ('US', 'Colorado', 'Denver', 'America/Denver'),
  ('US', 'Iowa', 'Des Moines', 'America/Chicago'),
  ('US', 'Michigan', 'Detroit', 'America/Detroit'),
  ('IE', NULL, 'Dublin', 'Europe/Dublin'),
  ('NZ', NULL, 'Dunedin', 'Pacific/Auckland'),
  ('US', 'North Carolina', 'Durham', 'America/New_York'),
  ('US', 'New York', 'East Village', 'America/New_York'),
  ('GB', NULL, 'Edinburgh', 'Europe/London'),
  ('CA', 'Alberta', 'Edmonton', 'America/Edmonton'),
  ('US', 'Texas', 'El Paso', 'America/Chicago'),
  ('US', 'North Dakota', 'Fargo', 'America/Chicago'),
  ('US', 'Colorado', 'Fort Collins', 'America/Denver'),
  ('US', 'Florida', 'Fort Lauderdale', 'America/New_York'),
  ('US', 'Florida', 'Fort Myers', 'America/New_York'),
  ('US', 'Texas', 'Fort Worth', 'America/Chicago'),
  ('US', 'California', 'Fresno', 'America/Los_Angeles'),
  ('US', 'Florida', 'Gainesville', 'America/New_York'),
  ('IE', NULL, 'Galway', 'Europe/Dublin'),
  ('GB', NULL, 'Glasgow', 'Europe/London'),
  ('AU', NULL, 'Gold Coast', 'Australia/Brisbane'),
  ('US', 'Michigan', 'Grand Rapids', 'America/Detroit'),
  ('US', 'South Carolina', 'Greenville', 'America/New_York'),
  ('CA', 'Ontario', 'Guelph', 'America/Toronto'),
  ('CA', 'Nova Scotia', 'Halifax', 'America/Halifax'),
  ('CA', 'Ontario', 'Hamilton', 'America/Toronto'),
  ('US', 'Connecticut', 'Hartford', 'America/New_York'),
  ('US', 'New Jersey', 'Hoboken', 'America/New_York'),
  ('US', 'Hawaii', 'Honolulu', 'Pacific/Honolulu'),
  ('US', 'Texas', 'Houston', 'America/Chicago'),
  ('US', 'Indiana', 'Indianapolis', 'America/Indiana/Indianapolis'),
  ('US', 'California', 'Irvine', 'America/Los_Angeles'),
  ('US', 'Mississippi', 'Jackson', 'America/Chicago'),
  ('US', 'Florida', 'Jacksonville', 'America/New_York'),
  ('US', 'New Jersey', 'Jersey City', 'America/New_York'),
  ('US', 'Missouri', 'Kansas City', 'America/Chicago'),
  ('CA', 'British Columbia', 'Kelowna', 'America/Vancouver'),
  ('US', 'Florida', 'Key West', 'America/New_York'),
  ('IE', NULL, 'Killarney', 'Europe/Dublin'),
  ('CA', 'Ontario', 'Kingston', 'America/Toronto'),
  ('US', 'Tennessee', 'Knoxville', 'America/Chicago'),
  ('US', 'Michigan', 'Lansing', 'America/Detroit'),
  ('US', 'Nevada', 'Las Vegas', 'America/Los_Angeles'),
  ('GB', NULL, 'Leeds', 'Europe/London'),
  ('GB', NULL, 'Leicester', 'Europe/London'),
  ('IE', NULL, 'Limerick', 'Europe/Dublin'),
  ('PT', NULL, 'Lisbon', 'Europe/Lisbon'),
  ('US', 'Arkansas', 'Little Rock', 'America/Chicago'),
  ('GB', NULL, 'Liverpool', 'Europe/London'),
  ('CA', 'Ontario', 'London', 'America/Toronto'),
  ('GB', NULL, 'London', 'Europe/London'),
  ('US', 'California', 'Long Beach', 'America/Los_Angeles'),
  ('US', 'California', 'Los Angeles', 'America/Los_Angeles'),
  ('US', 'Kentucky', 'Louisville', 'America/New_York'),
  ('US', 'New York', 'Lower East Village', 'America/New_York'),
  ('US', 'Wisconsin', 'Madison', 'America/Chicago'),
  ('ES', NULL, 'Madrid', 'Europe/Madrid'),
  ('GB', NULL, 'Manchester', 'Europe/London'),
  ('AU', NULL, 'Melbourne', 'Australia/Melbourne'),
  ('US', 'Tennessee', 'Memphis', 'America/Chicago'),
  ('US', 'Florida', 'Miami - Brickell', 'America/New_York'),
  ('US', 'Florida', 'Miami - South Beach', 'America/New_York'),
  ('US', 'Florida', 'Miami - Wynwood', 'America/New_York'),
  ('IT', NULL, 'Milan', 'Europe/Rome'),
  ('US', 'Wisconsin', 'Milwaukee', 'America/Chicago'),
  ('US', 'Minnesota', 'Minneapolis', 'America/Chicago'),
  ('US', 'Alabama', 'Montgomery', 'America/Chicago'),
  ('CA', 'Quebec', 'Montreal', 'America/Toronto'),
  ('DE', NULL, 'Munich', 'Europe/Berlin'),
  ('US', 'South Carolina', 'Myrtle Beach', 'America/New_York'),
  ('US', 'Tennessee', 'Nashville', 'America/Chicago'),
  ('US', 'Connecticut', 'New Haven', 'America/New_York'),
  ('US', 'Louisiana', 'New Orleans', 'America/Chicago'),
  ('US', 'New Jersey', 'Newark', 'America/New_York'),
  ('GB', NULL, 'Newcastle', 'Europe/London'),
  ('CA', 'Ontario', 'Niagara Falls', 'America/Toronto'),
  ('US', 'Virginia', 'Norfolk', 'America/New_York'),
  ('GB', NULL, 'Nottingham', 'Europe/London'),
  ('US', 'California', 'Oakland', 'America/Los_Angeles'),
  ('US', 'Maryland', 'Ocean City', 'America/New_York'),
  ('US', 'Nebraska', 'Omaha', 'America/Chicago'),
  ('US', 'Florida', 'Orlando', 'America/New_York'),
  ('CA', 'Ontario', 'Ottawa', 'America/Toronto'),
  ('US', 'Mississippi', 'Oxford', 'America/Chicago'),
  ('US', 'Florida', 'Panama City Beach', 'America/New_York'),
  ('AU', NULL, 'Perth', 'Australia/Perth'),
  ('US', 'Pennsylvania', 'Philadelphia', 'America/New_York'),
  ('US', 'Arizona', 'Phoenix', 'America/Phoenix'),
  ('US', 'Pennsylvania', 'Pittsburgh', 'America/New_York'),
  ('US', 'Texas', 'Plano', 'America/Chicago'),
  ('US', 'Oregon', 'Portland', 'America/Los_Angeles'),
  ('CZ', NULL, 'Prague', 'Europe/Prague'),
  ('US', 'Rhode Island', 'Providence', 'America/New_York'),
  ('CA', 'Quebec', 'Quebec City', 'America/Toronto'),
  ('US', 'North Carolina', 'Raleigh', 'America/New_York'),
  ('US', 'South Dakota', 'Rapid City', 'America/Chicago'),
  ('GB', NULL, 'Reading', 'Europe/London'),
  ('US', 'Nevada', 'Reno', 'America/Los_Angeles'),
  ('US', 'Virginia', 'Richmond', 'America/New_York'),
  ('US', 'New York', 'Rochester', 'America/New_York'),
  ('IT', NULL, 'Rome', 'Europe/Rome'),
  ('US', 'California', 'Sacramento', 'America/Los_Angeles'),
  ('US', 'Utah', 'Salt Lake City', 'America/Denver'),
  ('US', 'Texas', 'San Antonio', 'America/Chicago'),
  ('US', 'California', 'San Bernardino', 'America/Los_Angeles'),
  ('US', 'California', 'San Diego', 'America/Los_Angeles'),
  ('US', 'California', 'San Francisco', 'America/Los_Angeles'),
  ('US', 'California', 'San Jose', 'America/Los_Angeles'),
  ('US', 'Texas', 'San Marcos', 'America/Chicago'),
  ('US', 'California', 'Santa Barbara', 'America/Los_Angeles'),
  ('US', 'California', 'Santa Monica', 'America/Los_Angeles'),
  ('CA', 'Saskatchewan', 'Saskatoon', 'America/Regina'),
  ('US', 'Georgia', 'Savannah', 'America/New_York'),
  ('US', 'Arizona', 'Scottsdale', 'America/Phoenix'),
  ('US', 'Washington', 'Seattle', 'America/Los_Angeles'),
  ('GB', NULL, 'Sheffield', 'Europe/London'),
  ('US', 'Washington', 'Spokane', 'America/Los_Angeles'),
  ('CA', 'Newfoundland and Labrador', 'St. Johns', 'America/St_Johns'),
  ('US', 'Missouri', 'St. Louis', 'America/Chicago'),
  ('US', 'Florida', 'St. Petersburg', 'America/New_York'),
  ('US', 'Pennsylvania', 'State College', 'America/New_York'),
  ('AU', NULL, 'Surfers Paradise', 'Australia/Brisbane'),
  ('AU', NULL, 'Sydney', 'Australia/Sydney'),
  ('US', 'New York', 'Syracuse', 'America/New_York'),
  ('US', 'Florida', 'Tallahassee', 'America/New_York'),
  ('US', 'Florida', 'Tampa', 'America/New_York'),
  ('US', 'Arizona', 'Tempe', 'America/Phoenix'),
  ('US', 'Ohio', 'Toledo', 'America/New_York'),
  ('US', 'Arizona', 'Tucson', 'America/Phoenix'),
  ('US', 'Oklahoma', 'Tulsa', 'America/Chicago'),
  ('US', 'Alabama', 'Tuscaloosa', 'America/Chicago'),
  ('CA', 'British Columbia', 'Vancouver', 'America/Vancouver'),
  ('CA', 'British Columbia', 'Victoria', 'America/Vancouver'),
  ('US', 'District of Columbia', 'Washington', 'America/New_York'),
  ('IE', NULL, 'Waterford', 'Europe/Dublin'),
  ('CA', 'Ontario', 'Waterloo', 'America/Toronto'),
  ('NZ', NULL, 'Wellington', 'Pacific/Auckland'),
  ('US', 'California', 'West Hollywood', 'America/Los_Angeles'),
  ('CA', 'British Columbia', 'Whistler', 'America/Vancouver'),
  ('CA', 'Ontario', 'Windsor', 'America/Toronto'),
  ('CA', 'Manitoba', 'Winnipeg', 'America/Winnipeg'),
  ('US', 'Illinois', 'Chicago - Wrigleyville', 'America/Chicago'),
  ('US', 'Minnesota', 'St. Paul', 'America/Chicago'),
  ('DE', NULL, 'Cologne', 'Europe/Berlin'),
  ('US', 'Virginia', 'Virginia Beach', 'America/New_York'),
  ('CA', 'Alberta', 'Red Deer', 'America/Edmonton'),
  ('GB', NULL, 'Brighton', 'Europe/London'),
  ('CA', 'British Columbia', 'Kamloops', 'America/Vancouver'),
  ('CA', 'Alberta', 'Lethbridge', 'America/Edmonton'),
  ('US', 'Oregon', 'Eugene', 'America/Los_Angeles'),
  ('US', 'North Carolina', 'Asheville', 'America/New_York'),
  ('GB', NULL, 'Cambridge', 'Europe/London'),
  ('GB', NULL, 'Oxford', 'Europe/London'),
  ('GB', NULL, 'York', 'Europe/London'),
  ('AU', NULL, 'Newcastle', 'Australia/Sydney'),
  ('AU', NULL, 'Wollongong', 'Australia/Sydney'),
  ('GB', NULL, 'Aberdeen', 'Europe/London')
ON CONFLICT (country_code, region, name) DO NOTHING;

