"use server";

/**
 * Cross-domain handoff (Phase 2.14). [ReferenceDoc 6.2 / 9.1]
 *
 * After a venue's cold sequence exhausts (3 touches, no reply ->
 * cadence_state 'cold_exhausted_ready_for_handoff'), the operator can hand the
 * venue to a different outreach brand/domain, which runs its own fresh
 * sequence. A 7-day floor applies between the last touch from one domain and
 * the first touch from the next (venue sees both as the same brand).
 *
 * Data-model note: cold_outreach_entries carry no brand (brand is
 * campaign-level), and the sending domain is chosen at send time via the inbox
 * the operator picks. So a handoff RESETS the venue's thread cadence to
 * cold_pending_touch_1, re-attributes that thread to the target brand, and the
 * fresh T1 draft is generated by the composer (where the operator selects the
 * target brand's inbox/alias). No per-venue brand-override schema is invented.
 */

import {
  campaigns,
  cityCampaigns,
  coldOutreachEntries,
  emailThreads,
  outreachBrands,
  venueCampaignTouchLog,
} from "@/db/schema";
import { requireStaff } from "@/lib/auth";
import { CROSS_DOMAIN_FLOOR_DAYS, addDays } from "@/lib/cadence-engine-core";
import { db } from "@/lib/db";
import type { ActionResult } from "@/lib/form-utils";
import { logger } from "@/lib/logger";
import { and, desc, eq, ne } from "drizzle-orm";
import { revalidatePath } from "next/cache";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export interface HandoffBrandOption {
  brandId: string;
  brandName: string;
  emailDomain: string;
  /** ISO of the last touch this brand sent the venue, or null ("never"). */
  lastTouchFromBrandAt: string | null;
  /** True when the 7-day cross-domain floor allows sending from this brand now. */
  floorMet: boolean;
  /** ISO when the floor opens (null when already met). */
  floorAvailableAt: string | null;
}

/**
 * Alternative brands the venue can be handed to, each with its last-touch and
 * 7-day-floor state. Excludes the campaign's current brand.
 */
export async function loadHandoffOptions(
  venueId: string,
  cityCampaignId: string,
): Promise<HandoffBrandOption[]> {
  await requireStaff();
  if (!UUID_RE.test(venueId) || !UUID_RE.test(cityCampaignId)) return [];

  const [cc] = await db
    .select({
      campaignId: cityCampaigns.campaignId,
      currentBrandId: campaigns.outreachBrandId,
    })
    .from(cityCampaigns)
    .innerJoin(campaigns, eq(campaigns.id, cityCampaigns.campaignId))
    .where(eq(cityCampaigns.id, cityCampaignId))
    .limit(1);
  if (!cc) return [];

  const brands = await db
    .select({
      id: outreachBrands.id,
      name: outreachBrands.displayName,
      emailDomain: outreachBrands.emailDomain,
    })
    .from(outreachBrands)
    .where(
      and(
        eq(outreachBrands.status, "active"),
        cc.currentBrandId ? ne(outreachBrands.id, cc.currentBrandId) : undefined,
      ),
    );
  if (brands.length === 0) return [];

  // Every touch for this venue x campaign (a handful of rows) -> per-brand last
  // touch + the cross-domain floor computed in memory.
  const touches = await db
    .select({
      brandId: venueCampaignTouchLog.outreachBrandId,
      sentAt: venueCampaignTouchLog.sentAt,
    })
    .from(venueCampaignTouchLog)
    .where(
      and(
        eq(venueCampaignTouchLog.venueId, venueId),
        eq(venueCampaignTouchLog.campaignId, cc.campaignId),
      ),
    )
    .orderBy(desc(venueCampaignTouchLog.sentAt));

  const now = new Date();
  return brands.map((b) => {
    const fromBrand = touches.find((t) => t.brandId === b.id)?.sentAt ?? null;
    // Floor = 7 days since the most recent touch from a DIFFERENT brand.
    const mostRecentOther = touches.find((t) => t.brandId !== b.id)?.sentAt ?? null;
    const floorAt = mostRecentOther ? addDays(mostRecentOther, CROSS_DOMAIN_FLOOR_DAYS) : null;
    const floorMet = !floorAt || floorAt.getTime() <= now.getTime();
    return {
      brandId: b.id,
      brandName: b.name,
      emailDomain: b.emailDomain,
      lastTouchFromBrandAt: fromBrand ? fromBrand.toISOString() : null,
      floorMet,
      floorAvailableAt: floorMet || !floorAt ? null : floorAt.toISOString(),
    };
  });
}

/**
 * Hand a venue to a different brand: re-check the 7-day floor, reset the
 * venue's thread cadence to cold_pending_touch_1, and re-attribute the thread
 * to the target brand. The caller then opens a fresh cold draft in the
 * composer (which engine-picks T1).
 */
export async function handoffColdOutreach(input: {
  entryId: string;
  targetBrandId: string;
}): Promise<ActionResult<{ venueId: string; cityCampaignId: string; targetBrandId: string }>> {
  await requireStaff();
  if (!UUID_RE.test(input.entryId) || !UUID_RE.test(input.targetBrandId)) {
    return { ok: false, error: "Invalid id." };
  }
  try {
    const [entry] = await db
      .select({
        venueId: coldOutreachEntries.venueId,
        cityCampaignId: coldOutreachEntries.cityCampaignId,
      })
      .from(coldOutreachEntries)
      .where(eq(coldOutreachEntries.id, input.entryId))
      .limit(1);
    if (!entry) return { ok: false, error: "Entry not found." };

    // Server-authoritative floor re-check (don't trust the client).
    const options = await loadHandoffOptions(entry.venueId, entry.cityCampaignId);
    const target = options.find((o) => o.brandId === input.targetBrandId);
    if (!target) return { ok: false, error: "That brand isn't available for handoff." };
    if (!target.floorMet) {
      const when = target.floorAvailableAt
        ? new Date(target.floorAvailableAt).toLocaleDateString("en-CA")
        : "soon";
      return { ok: false, error: `7-day cross-domain floor -- available ${when}.` };
    }

    // Scope the handoff to the EXHAUSTED COLD thread only (P0-6). A handoff
    // resets cadence to a fresh cold touch 1; doing that to warm/confirmed/
    // lifecycle/declined threads for the same venue x campaign would corrupt
    // their state. Pre-check the current state so we fail friendly instead of
    // silently no-op'ing, then constrain the UPDATE to the exhausted-cold state.
    const [thread] = await db
      .select({ id: emailThreads.id, cadenceState: emailThreads.cadenceState })
      .from(emailThreads)
      .where(
        and(
          eq(emailThreads.venueId, entry.venueId),
          eq(emailThreads.cityCampaignId, entry.cityCampaignId),
          eq(emailThreads.cadenceState, "cold_exhausted_ready_for_handoff"),
        ),
      )
      .limit(1);
    if (!thread) {
      return {
        ok: false,
        error: "This thread is not an exhausted cold sequence; nothing to hand off.",
      };
    }

    await db
      .update(emailThreads)
      .set({
        cadenceState: "cold_pending_touch_1",
        cadenceNextDueAt: new Date(),
        outreachBrandId: input.targetBrandId,
      })
      .where(
        and(
          eq(emailThreads.venueId, entry.venueId),
          eq(emailThreads.cityCampaignId, entry.cityCampaignId),
          eq(emailThreads.cadenceState, "cold_exhausted_ready_for_handoff"),
        ),
      );

    logger.info(
      {
        entryId: input.entryId,
        threadId: thread.id,
        venueId: entry.venueId,
        cityCampaignId: entry.cityCampaignId,
        targetBrandId: input.targetBrandId,
        fromCadenceState: thread.cadenceState,
        toCadenceState: "cold_pending_touch_1",
      },
      "handoffColdOutreach: handed off exhausted cold thread to target brand",
    );

    revalidatePath(`/city-campaigns/${entry.cityCampaignId}`);
    return {
      ok: true,
      data: {
        venueId: entry.venueId,
        cityCampaignId: entry.cityCampaignId,
        targetBrandId: input.targetBrandId,
      },
    };
  } catch (err) {
    logger.error({ err, entryId: input.entryId }, "handoffColdOutreach failed");
    return { ok: false, error: "Couldn't hand off this venue." };
  }
}
