#!/usr/bin/env bash
# scripts/install-sheets-backup-cron.sh
#
# Idempotent installer for the daily Google Sheets backup cron.
# Drops /etc/cron.d/outreach-sheets-backup that runs the backup
# script at 04:00 UTC every day and tees output to a rotated log.
#
# Run once per VPS (as root). Safe to re-run — `cat >` replaces the
# file with the same content.
#
# Prereqs:
#   1. /var/www/outreach has been deployed at least once
#   2. /root/outreach-secrets/sheets-service-account.json exists
#      (downloaded from Google Cloud Console, chmod 600 root:root)
#   3. /var/www/outreach/.env has these vars set:
#        SHEETS_BACKUP_SPREADSHEET_ID
#        SHEETS_BACKUP_CAMPAIGN_SLUG
#        SHEETS_BACKUP_SA_KEY_PATH  (optional, defaults to the path above)
#
# After running this once, verify with:
#     sudo run-parts --test /etc/cron.d  # lists the file
#     cat /etc/cron.d/outreach-sheets-backup
#     bash -c 'cd /var/www/outreach && npm run backup:sheets'  # dry-run
set -euo pipefail

CRON_FILE=/etc/cron.d/outreach-sheets-backup
LOG_FILE=/var/log/outreach-sheets-backup.log

if [[ $EUID -ne 0 ]]; then
  echo "must be run as root (uses /etc/cron.d)"
  exit 1
fi

# Make sure the log file exists and is writable BEFORE cron runs so
# the first execution doesn't fail on a permission error.
touch "$LOG_FILE"
chmod 640 "$LOG_FILE"

# /etc/cron.d entries need a user column (unlike crontab -e). Run as
# root so npm + the service-account key (root-owned, 600) are
# reachable.
#
# `flock -n` prevents two runs piling up if a previous one hangs (a
# slow Google API call shouldn't queue tomorrow's run behind it).
cat > "$CRON_FILE" <<'EOF'
# /etc/cron.d/outreach-sheets-backup
# Generated by scripts/install-sheets-backup-cron.sh — re-run that to update.

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# m  h dom mon dow user command
0  4 *   *   *   root /usr/bin/flock -n /tmp/outreach-sheets-backup.lock bash -c 'cd /var/www/outreach && /usr/bin/npm run --silent backup:sheets >> /var/log/outreach-sheets-backup.log 2>&1'
EOF

chmod 644 "$CRON_FILE"

echo "installed $CRON_FILE"
echo "tail of cron file:"
cat "$CRON_FILE"
echo
echo "log file:       $LOG_FILE"
echo "next run (UTC): tomorrow 04:00"
echo
echo "to test now:    cd /var/www/outreach && npm run backup:sheets"
